services:
  api-main:
    build:
      context: ../
    restart: always
    ports:
      - "7777:8000"
    env_file:
      - app/.env
    networks:
      - telega-network

networks:
  telega-network:
    driver: bridge