services:
  api-main:
    build:
      context: ../
    restart: always
    volumes:
      - ../prompt.yaml:/code/prompt.yaml
      - ../embeddings:/code/models
      - .data/chroma:/code/chroma.db
    ports:
      - "7777:8000"
    env_file:
      - app/.env
    networks:
      - telega-network

  redis:
    image: redis
    restart: always
    networks:
      - telega-network

networks:
  telega-network:
    driver: bridge